name: Build Docker Image

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Image
        run: bash scripts/build-docker.sh
